# Generated by cucumber-sinatra. (Wed Sep 08 09:51:48 +1000 2010)

require File.join(File.dirname(__FILE__), '..', '..', 'lib/cuke_sin.rb')

require 'capybara'
require 'capybara/cucumber'
require 'spec'

CukeSin.set(:environment, :test)

Capybara.app = CukeSin

class CukeSinWorld
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end

World do
  CukeSinWorld.new
end
